const ENG_AUDIO = {
  "birthday card": "assets/audio/word-card.wav",
  "water": "assets/audio/word-water.wav",
  "crisps": "assets/audio/word-crisps.wav",
  "pizza": "assets/audio/word-pizza.wav",
  "popcorn": "assets/audio/word-popcorn.wav",
  "yoghurt": "assets/audio/word-yoghurt.wav",
  "sausages": "assets/audio/word-sausages.wav",
  "cherries": "assets/audio/word-cherries.wav",
  "potatoes": "assets/audio/word-potatoes.wav",
  "onions": "assets/audio/word-onions.wav",
  "mushrooms": "assets/audio/word-mushrooms.wav",
  "pot": "assets/audio/word-pot.wav",
  "She likes water.": "assets/audio/likes-water.wav",
  "He doesn't like yoghurt.": "assets/audio/likes-yoghurt.wav",
  "She doesn't like pizza.": "assets/audio/likes-pizza.wav",
  "He likes crisps.": "assets/audio/likes-crisps.wav",
  "Have you got potatoes? Yes, I have.": "assets/audio/got-potatoes-yes.wav",
  "Have you got onions? No, I haven't.": "assets/audio/got-onions-no.wav",
  "Have you got mushrooms? No, I haven't.": "assets/audio/got-mushrooms-no.wav",
  "Have you got a pot? Yes, I have.": "assets/audio/got-pot-yes.wav",
  "Have you got potatoes? No, I haven't.": "assets/audio/got-potatoes-no.wav",
  "Have you got onions? Yes, I have.": "assets/audio/got-onions-yes.wav",
  "Have you got mushrooms? Yes, I have.": "assets/audio/got-mushrooms-yes.wav",
  "Have you got a pot? No, I haven't.": "assets/audio/got-pot-no.wav",
  "Have you got a pot?": "assets/audio/question-pot.wav",
  "Yes, I have.": "assets/audio/answer-yes.wav",
  "No, I haven't.": "assets/audio/answer-no.wav"
};
