'use strict';
const $=id=>document.getElementById(id);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected='lendas',run=null,wrun=null,records={};
try{records=JSON.parse(localStorage.getItem('julia-portugues-v1')||'{}')||{};}catch{}
function save(){try{localStorage.setItem('julia-portugues-v1',JSON.stringify(records));}catch{}renderHome();}
function screen(id){if(typeof stopEnglishAudio==='function')stopEnglishAudio();document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo(0,0);if(id==='writing')requestAnimationFrame(resizeCanvas);}
function renderHome(){$('topics').innerHTML=TOPICS.map(([id,emoji,title,sub])=>`<button class="topic-card" data-topic="${id}"><div class="art ${id}" aria-hidden="true"></div><span class="caption"><strong>${emoji} ${title}</strong><small>${sub}</small><small class="chip">${records[id]?`Melhor rodada: ${records[id].correct}/${records[id].total}`:'Comece uma descoberta'}</small></span></button>`).join('');$('topics').querySelectorAll('button').forEach(b=>b.onclick=()=>openTopic(b.dataset.topic));$('progress').textContent='Seus registros ficam apenas neste navegador. '+Object.keys(records).filter(k=>k!=='mix').length+' de 6 trilhas praticadas.';}
function readingHTML(id){const t=TEXTS[id];return `<p class="eyebrow">LEITURA · PÁGINAS ${t.pages}</p><h2>${escapeHTML(t.title)}</h2>${t.by?`<p><strong>Por ${t.by}</strong><br>Publicado em ${t.date}</p>`:''}${t.paras.map(p=>p.startsWith('Parte ')||p.startsWith('[…] Saci')||p==='[…] Boitatá'||p==='[…] Cuca'?`<h3>${escapeHTML(p)}</h3>`:`<p>${escapeHTML(p)}</p>`).join('')}${t.note?`<p class="note">${escapeHTML(t.note)}</p>`:''}${t.bio?`<h3>Conheça a escritora</h3><p>${escapeHTML(t.bio)}</p>`:''}${id==='escrita'?'<h3>Observe um modelo cursivo</h3><p class="cursive">O Saci-Pererê consegue ficar invisível.</p><p class="small">Cursiva maiúscula e minúscula. O formato pode variar entre modelos.</p><p class="letters">A B C D E F G H I J K L M N O P Q R S T U V W X Y Z</p>':''}${t.credit?`<p class="credit">${escapeHTML(t.credit)}</p>`:''}`;}
function openTopic(id){selected=id;const t=TOPICS.find(x=>x[0]===id);$('topic-title').textContent=t[2];$('topic-pages').textContent='Páginas '+TEXTS[id].pages;$('topic-art').className='art banner '+id;$('reading').innerHTML=readingHTML(id);screen('topic');}
function shuffle(a){const copy=a.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function startQuiz(id){const pool=id==='mix'?TOPICS.flatMap(([topic])=>QUESTIONS[topic].map(p=>({...p,topic}))):QUESTIONS[id].map(p=>({...p,topic:id}));const chosen=id==='mix'?shuffle(TOPICS.flatMap(([topic])=>shuffle(QUESTIONS[topic]).slice(0,3).map(p=>({...p,topic})))):pool;run={id,items:chosen.map(p=>{const opts=shuffle(p.options.map((text,i)=>({text,correct:i===p.answer})));return {...p,opts};}),i:0,correct:0,answered:false};screen('quiz');loadQuestion();}
function loadQuestion(){const p=run.items[run.i];run.answered=false;$('quiz-title').textContent=run.id==='mix'?'⭐ Revisão de todas as trilhas':TOPICS.find(t=>t[0]===run.id)[2];$('quiz-count').textContent=`${run.i+1} de ${run.items.length}`;$('bar').max=run.items.length;$('bar').value=run.i;$('source').textContent='Base: página '+p.page;$('question').textContent=p.text;$('support-body').innerHTML=readingHTML(p.topic);$('support').open=false;$('feedback').hidden=true;$('next').hidden=true;$('options').innerHTML=p.opts.map((o,i)=>`<button class="option" data-index="${i}">${escapeHTML(o.text)}</button>`).join('');$('options').querySelectorAll('button').forEach(b=>b.onclick=()=>answer(Number(b.dataset.index)));}
function answer(i){if(run.answered)return;run.answered=true;const p=run.items[run.i],ok=p.opts[i].correct;if(ok)run.correct++;$('options').querySelectorAll('button').forEach((b,n)=>{b.disabled=true;if(p.opts[n].correct){b.classList.add('correct');b.textContent='✓ '+p.opts[n].text;}else if(n===i){b.classList.add('wrong');b.textContent='↻ '+p.opts[n].text;}});$('feedback').className='feedback'+(ok?'':' miss');$('feedback').textContent=(ok?'Muito bem! ':'Vamos conferir: ')+p.why;$('feedback').hidden=false;$('next').hidden=false;$('next').textContent=run.i===run.items.length-1?'Ver minha rodada →':'Próxima →';$('bar').value=run.i+1;}
function next(){if(!run.answered)return;if(++run.i<run.items.length){loadQuestion();window.scrollTo(0,0);}else{const old=records[run.id];if(!old||run.correct/run.items.length>old.correct/old.total)records[run.id]={correct:run.correct,total:run.items.length};save();$('result-title').textContent='Rodada concluída, Julia!';$('result-score').textContent=`${run.correct} de ${run.items.length} respostas corretas`;$('result-note').textContent='Cada descoberta conta. Você pode reler o texto e tentar de novo.';$('again').onclick=()=>startQuiz(run.id);screen('result');}}
function startWriting(){wrun={id:selected,i:0};loadWriting();screen('writing');}
function loadWriting(){const [prompt,model,page]=WRITING[wrun.id][wrun.i];$('write-count').textContent=`Atividade ${wrun.i+1} de ${WRITING[wrun.id].length} · página ${page}`;$('write-prompt').textContent=prompt;$('write-support').innerHTML=readingHTML(wrun.id);$('typed').value='';$('write-feedback').hidden=true;$('write-next').hidden=true;$('compare').hidden=false;strokes=[];activePointer=null;draw();$('write-next').textContent=wrun.i===WRITING[wrun.id].length-1?'Concluir meu treino →':'Próxima atividade →';}
function compare(){$('write-feedback').textContent='Compare com um adulto: '+WRITING[wrun.id][wrun.i][1]+' A sua escrita e o seu desenho não foram corrigidos automaticamente.';$('write-feedback').hidden=false;$('write-next').hidden=false;$('compare').hidden=true;}
function nextWriting(){if(++wrun.i<WRITING[wrun.id].length){loadWriting();window.scrollTo(0,0);}else{$('result-title').textContent='Treino de escrita concluído!';$('result-score').textContent=WRITING[wrun.id].length+' atividades exploradas';$('result-note').textContent='Confira suas respostas com um adulto. Escrever ou desenhar não significa que a resposta foi corrigida.';$('again').onclick=startWriting;screen('result');}}
const canvas=$('canvas'),ctx=canvas.getContext('2d');let strokes=[],activePointer=null,cw=0,ch=0;
function resizeCanvas(){if(!$('writing').classList.contains('active'))return;const r=canvas.getBoundingClientRect();cw=r.width;ch=r.height;const d=Math.min(window.devicePixelRatio||1,3);canvas.width=Math.round(cw*d);canvas.height=Math.round(ch*d);ctx.setTransform(d,0,0,d,0,0);draw();}
function draw(){ctx.clearRect(0,0,cw,ch);if($('lines').value==='lines'){ctx.strokeStyle='#dce6e5';ctx.lineWidth=1;for(let y=38;y<ch;y+=38){ctx.beginPath();ctx.moveTo(14,y);ctx.lineTo(cw-14,y);ctx.stroke();}}ctx.strokeStyle='#223f4b';ctx.fillStyle='#223f4b';ctx.lineWidth=3;ctx.lineCap='round';ctx.lineJoin='round';for(const stroke of strokes){ctx.beginPath();if(stroke.length===1){ctx.arc(stroke[0].x*cw,stroke[0].y*ch,1.5,0,Math.PI*2);ctx.fill();}else{ctx.moveTo(stroke[0].x*cw,stroke[0].y*ch);stroke.slice(1).forEach(p=>ctx.lineTo(p.x*cw,p.y*ch));ctx.stroke();}}}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};}
canvas.addEventListener('pointerdown',e=>{if(activePointer!==null||e.isPrimary===false)return;e.preventDefault();activePointer=e.pointerId;canvas.setPointerCapture(e.pointerId);strokes.push([point(e)]);draw();});canvas.addEventListener('pointermove',e=>{if(activePointer!==e.pointerId)return;e.preventDefault();const list=e.getCoalescedEvents?e.getCoalescedEvents():[e];(list.length?list:[e]).forEach(ev=>strokes[strokes.length-1].push(point(ev)));draw();});function end(e){if(activePointer!==e.pointerId)return;activePointer=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('lostpointercapture',()=>activePointer=null);canvas.addEventListener('contextmenu',e=>e.preventDefault());new ResizeObserver(resizeCanvas).observe(canvas.parentElement);
$('undo').onclick=()=>{strokes.pop();draw();};$('clear').onclick=()=>{strokes=[];draw();};$('lines').onchange=draw;$('compare').onclick=compare;$('write-next').onclick=nextWriting;$('write-back').onclick=()=>openTopic(selected);$('practice').onclick=$('practice-bottom').onclick=()=>startQuiz(selected);$('write').onclick=startWriting;$('read').onclick=()=>{$('reading').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};$('mix').onclick=()=>startQuiz('mix');$('next').onclick=next;document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>screen('home'));$('reset').onclick=()=>{if(confirm('Recomeçar os registros de estudo neste navegador?')){records={};save();}};
// A identificação do tipo de letra depende de um modelo visual utilizável.
q('escrita','Observe a frase em cursiva no apoio. Que tipos de letra ela apresenta?',['Cursiva maiúscula e minúscula','Somente cursiva maiúscula','Somente letra de imprensa maiúscula','Somente letra de imprensa minúscula'],0,'O modelo cursivo usa maiúsculas no início e no nome Saci-Pererê, e minúsculas no restante.',107);
renderHome();
