const TEXTS = {
 lendas: {title:'Criaturas das lendas brasileiras',pages:'106–109',paras:[
'[…] Saci-Pererê',
'Ele adora aprontar! Entra nas casas, apaga a chama dos fogões e faz as pessoas se perderem nas estradas. Pulando em apenas uma perna, teria poderes vindos de um gorro vermelho — como ficar invisível e soltar um assobio que parece vir de lugar nenhum!',
'[…] Boitatá',
'Há quem diga que, pelos campos e matas brasileiros, existe uma cobra de fogo. É Boitatá, que se transforma em um pedaço de madeira em brasa para queimar quem tenta incendiar as florestas. Ela seria a única sobrevivente de um grande dilúvio que cobriu a Terra.',
'[…] Cuca',
'É o mais conhecido dos bichos-papões. Tem cabeça de jacaré e surge durante a noite para levar embora crianças mal-educadas. Dizem que ela dorme apenas uma noite a cada sete anos e, quando fica brava, solta um grito que pode ser ouvido de muito longe!'],credit:'Recreio | Perfil.com Ltda. Trechos apresentados no livro.',note:'Dilúvio é uma enchente causada por chuvas tão fortes que acabam cobrindo grandes áreas.'},
 peter:{title:'Peter Pan',pages:'177–180',paras:[
'Os irmãos Wendy, João e Miguel moravam em uma aconchegante casa em Londres, na Inglaterra. Certa noite, Wendy, a irmã mais velha, preparava-se para contar uma história de aventura para os irmãos antes de dormir. De repente, em um brilho cintilante, apareceu na janela do quarto um menino com roupas verdes.',
'O garoto se chamava Peter Pan e havia muito tempo que ele era criança, pois o menino nunca crescia. Peter Pan vivia na Terra do Nunca, a terra da imaginação e dos sonhos, um lugar mágico onde ninguém envelhece. No entanto, o menino adorava visitar o mundo real de vez em quando, em busca de novas aventuras.',
'Peter convidou os três irmãos para conhecerem a Terra do Nunca. Explicou que, para essa viagem fantástica, precisavam apenas do pó mágico da Fada Sininho e de pensamentos felizes. Assim eles conseguiriam voar até a terra da magia.',
'Os irmãos aceitaram o convite e, então, todos voaram sobre os telhados da cidade de Londres, cruzando nuvens e estrelas, até chegarem à misteriosa Terra do Nunca.',
'Nessa terra encantada, os irmãos conheceram os Meninos Perdidos, que eram amigos fiéis liderados por Peter Pan. Lá todos eram livres para brincar e se divertir. Juntos, eles exploraram cavernas, construíram cabanas em árvores, navegaram por mares agitados e precisaram combater piratas, principalmente o Capitão Gancho, o grande inimigo de Peter, que tinha um gancho no lugar de uma das mãos.',
'Depois de dias mágicos vividos na Terra do Nunca, Wendy e os irmãos começaram a sentir saudades dos pais. Então Peter Pan e a Fada Sininho os levaram de volta para casa, deixando-os na janela do quarto deles em Londres.',
'Na manhã seguinte, os irmãos acordaram com a sensação de que a viagem à Terra do Nunca pudesse ter sido apenas um sonho, mas que deixou memórias inesquecíveis.',
'Enquanto isso, Peter Pan e a Fada Sininho retornaram à terra da magia, onde continuaram suas aventuras, lembrando sempre da importância de manter pensamentos felizes e não deixar a magia da infância desaparecer.'],credit:'Texto do livro elaborado com base na obra Peter Pan in Kensington Gardens, de J. M. Barrie, em domínio público.',note:'O conto fantástico mistura elementos fantasiosos com elementos reais. No final, pode ficar a dúvida: foi sonho ou realidade?'},
 alice:{title:'Alice no País das Maravilhas',pages:'181–187',paras:[
'Parte 1',
'Alice era uma menina alegre que adorava explorar lugares diferentes.',
'Em uma tarde ensolarada, ela estava sentada debaixo de uma árvore, lendo um livro com sua irmã.',
'De repente, Alice viu um coelho branco vestindo um colete e carregando um relógio. Ele exclamou, apressado:',
'— Oh, não! Estou atrasado!',
'O coelho correu e pulou dentro de um buraco no chão. Alice ficou tão curiosa que decidiu segui-lo. E, então, ela caiu no buraco, que era muito fundo, e foi parar em um mundo desconhecido, o País das Maravilhas […].',
'Parte 2',
'Alice percebeu que estava em um lugar muito estranho, com um corredor cheio de portas trancadas. Em cima de uma mesa, havia uma chave bem pequena, que cabia na fechadura de uma portinha no fim do corredor. Alice conseguiu abri-la, mas a porta era tão pequena que a menina não conseguia passar por ela.',
'Nesse momento, Alice viu uma garrafinha no canto da mesa, com um rótulo que dizia: “Beba-me”. Ela pegou a garrafa e tomou um gole. Imediatamente, a menina começou a encolher, até ficar do tamanho de uma pequena boneca. E, assim, ela conseguiu entrar pela porta e avistou novamente o coelho, que seguia por uma floresta encantadora.',
'No caminho da floresta, Alice encontrou criaturas muito diferentes! Ela conheceu um gato de sorriso largo, que dizia coisas confusas, e uma lagarta azul que fazia muitas perguntas e dava respostas estranhas. Também conversou com um chapeleiro maluco e uma lebre engraçada que tomavam chá juntos todos os dias. Eles a receberam bem, mas a conversa era tão maluca que Alice ficou confusa […].',
'Parte 3',
'Alice continuou sua aventura e conheceu a Rainha de Copas, que era muito mandona. A rainha sempre jogava o mesmo jogo, todos os dias. Ela desafiou Alice em uma partida, mas a menina ganhou e a rainha ficou furiosa.',
'Alice saiu correndo em disparada. Aquele mundo era tão esquisito e diferente do que ela conhecia!',
'De repente, tudo começou a girar ao redor dela. E então… Alice acordou!',
'Ela contou toda a história para a irmã e nunca mais se esqueceu do País das Maravilhas. No entanto, Alice ficou se questionando… será que tudo tinha sido apenas um sonho? Ou será que aquela aventura tinha sido real?'],credit:'Texto do livro elaborado com base na obra Alice’s Adventures in Wonderland, de Lewis Carroll, em domínio público.'},
 escrita:{title:'Que letra bonita!',pages:'107–109, 182–183, 187, 197',paras:[
'Usamos letras maiúsculas no início das frases e nos nomes próprios, como Alice, Peter Pan e Inaiá.',
'Ao escrever, deixe espaços entre as palavras. Em uma frase afirmativa como “O menino gostava de histórias fantásticas.”, use ponto-final.',
'A letra cursiva tem seu próprio traçado. Observe o modelo e pratique à mão, com calma.',
'Títulos trabalhados no livro: Descobertas de Inaiá e O Grúfalo.',
'Para colocar palavras em ordem alfabética, compare as letras. Se o começo for igual, continue até encontrar uma letra diferente.',
'Exemplo: Jogo da Memória vem antes de Jogo da Velha, porque M vem antes de V.',
'Lista em ordem alfabética: Dama, Dominó, Ludo, Quebra-cabeça, Xadrez.'],note:'Estas são orientações de revisão baseadas nas atividades do livro.'},
 silabas:{title:'Sílaba por sílaba',pages:'193–197',paras:[
'Na história em quadrinhos, as crianças comentam Peter Pan, Alice no País das Maravilhas e A Bela Adormecida. Voar com pó de fada, encolher e dormir por cem anos são situações fantasiosas.',
'As letras RR e SS são consoantes que se repetem nas palavras formando um único som. Na separação silábica, cada letra deve ficar em uma sílaba diferente.',
'Exemplos: cor-ri-da, pas-sa-tem-po, sor-ri-den-te, a-pres-sa-do.',
'Outras palavras do livro: mun-do, bu-ra-co, ga-to, pa-ís, la-gar-ta, es-qui-si-to, fa-da, ga-ro-ta, ma-ra-vi-lho-so.',
'Quando uma palavra inteira não cabe no fim da linha, podemos continuar na próxima linha, respeitando suas sílabas e usando hífen.',
'Exemplos do treino de fim de linha: bos- / que, gran- / dinhos, mui- / to, rou- / pas, ergueri- / am, for- / ma. A barra indica a mudança de linha.',
'Use as linhas e as margens com organização. Evite espalhar demais as letras ou os espaços entre as palavras.'],note:'O hífen marca a divisão da palavra; o restante continua na linha seguinte.'},
 noticia:{title:'Como uma pergunta ouvida por Ana Maria Machado de sua filha há mais de 40 anos virou seu novo livro',pages:'199–201',by:'Maria Eduarda Gomes',date:'14/09/2024',paras:[
'[…] escritora que formou gerações de leitores fala sobre sua obra para crianças, [e] conta […] o que a motiva a seguir produzindo aos 82 anos.',
'[…] a autora de livros infantis e adultos Ana Maria Machado acumula mais de 100 publicações de livros no Brasil, 20 traduzidas para outros idiomas […]. Com mais de 60 anos de carreira, ela ainda cumpre compromissos literários e presença em eventos, como na Bienal do Livro nesta semana […] para falar sobre a publicação de […] obras e ser entrevistada por crianças.',
'O livro Sem Fim, Joaquim […] narra a história de um menino que deseja contar tudo à sua volta, das folhas das árvores aos grãos de areia, até que descobre o significado de “infinito” […].',
'A inspiração para a construção dessa obra aconteceu há cerca de 40 anos, quando sua filha Luísa, na época aos 5 anos, perguntou se poderia contar os grãos de areia da praia em que estavam, no Espírito Santo. “Foi uma observação dela, na época. Ela perguntava quantas conchas tinham na praia, quantos peixinhos tinham no mar, quantas gotas de água tinham no mar”, lembra Ana Maria Machado. Em um estalo, a autora se lembrou desse episódio de descobertas de sua filha, e resolveu que daria uma boa história infantil.',
'[…] a literatura faz parte de sua vida desde pequena. A criatividade da autora vem de seu contato com a palavra literária desde seus primeiros anos, ainda quando sua avó lia histórias a ela […].',
'Entre todas as suas inspirações para criar novas histórias, o meio ambiente também causa entusiasmo, um exemplo disso é seu livro Gente, Bicho, Planta: O mundo me encanta […].',
'[Ana Maria] menciona que, apesar da idade, […] ainda escreve muito e idealiza projetos futuros.'],credit:'O Estado de S. Paulo. Maria Eduarda Gomes, 14 set. 2024. Trechos apresentados no livro.',note:'Notícia transmite informações sobre pessoas e acontecimentos reais. O título da notícia é chamado de manchete. Notícias são divulgadas em meios de comunicação.',bio:'Ana Maria Machado nasceu no município do Rio de Janeiro, em 1941. Começou sua carreira profissional como pintora, professora e jornalista. Mais tarde, passou a se dedicar à escrita de livros e foi uma das fundadoras da primeira livraria infantil do Brasil. Suas obras abordam temas como imaginação, liberdade e valores.'}
};
const TOPICS=[['lendas','🌿','Lendas brasileiras','Saci, Boitatá e Cuca'],['peter','✨','Peter Pan','Uma viagem à Terra do Nunca'],['alice','🐇','Alice','Três partes de uma aventura'],['escrita','🔎','Escrita e alfabeto','Maiúsculas, espaços e cursiva'],['silabas','👏','Sílabas','RR, SS e fim de linha'],['noticia','📰','Fatos que inspiram','Notícia e Ana Maria Machado']];
const QUESTIONS={};
function q(topic,text,options,answer,why,page){(QUESTIONS[topic]??=[]).push({text,options,answer,why,page});}
q('lendas','De qual objeto vêm os poderes do Saci-Pererê?',['Um gorro vermelho','Um relógio de bolso','Uma chave pequena','Um colete azul'],0,'O texto diz que os poderes viriam de um gorro vermelho.',107);
q('lendas','Onde vive o Boitatá, segundo o texto?',['Nos campos e matas brasileiros','Nos telhados de Londres','Em um corredor de portas','No quarto de Wendy'],0,'A lenda situa o Boitatá nos campos e matas brasileiros.',107);
q('lendas','Que tipo de animal é o Boitatá?',['Uma cobra de fogo','Um coelho branco','Um gato sorridente','Uma lagarta azul'],0,'No texto, Boitatá é uma cobra de fogo.',107);
q('lendas','O que significa “dilúvio” no glossário?',['Uma enchente causada por chuvas muito fortes','Um assobio que vem de longe','Um pedaço de madeira em brasa','Um grito de uma criatura'],0,'O glossário explica que essas chuvas podem cobrir grandes áreas.',106);
q('lendas','Que ação é atribuída ao Saci no texto?',['Apagar a chama dos fogões','Tomar um gole e encolher','Contar todos os grãos de areia','Construir uma casa de palha'],0,'O Saci entra nas casas e apaga a chama dos fogões.',106);
q('lendas','Como é a cabeça da Cuca?',['De jacaré','De coelho','De gato','De cobra'],0,'O texto descreve a Cuca com cabeça de jacaré.',106);
q('lendas','Segundo a lenda, com que frequência a Cuca dorme?',['Uma noite a cada sete anos','Todas as noites','Sete noites a cada ano','Cem anos sem acordar'],0,'A lenda diz: apenas uma noite a cada sete anos.',106);
q('lendas','Qual característica do Saci é descrita no texto?',['Ele pula em uma perna','Ele tem um gancho na mão','Ele carrega uma chave','Ele é uma cobra de fogo'],0,'O texto diz “Pulando em apenas uma perna”.',106);
q('peter','Para que Wendy se preparava naquela noite?',['Contar uma história aos irmãos','Jantar com os Meninos Perdidos','Comprar uma passagem','Pescar perto de um lago'],0,'Wendy ia contar uma história de aventura antes de os irmãos dormirem.',178);
q('peter','O que apareceu na janela do quarto?',['Um menino com roupas verdes','Um coelho com relógio','Uma cobra de fogo','Uma rainha furiosa'],0,'Esse trecho está no primeiro parágrafo.',178);
q('peter','Por que Peter Pan nunca crescia, segundo a história?',['Vivia na Terra do Nunca, onde ninguém envelhece','Dormia por cem anos','Contava grãos de areia','Usava uma chave pequena'],0,'A Terra do Nunca é descrita como um lugar mágico onde ninguém envelhece.',178);
q('peter','Qual dupla reúne o necessário para voar até a Terra do Nunca?',['Pó mágico da Fada Sininho e pensamentos felizes','Passagem comprada e relógio','Chave pequena e garrafinha','Gorro vermelho e colete'],0,'Peter explica que precisavam do pó mágico e de pensamentos felizes.',178);
q('peter','Quem eram os Meninos Perdidos?',['Amigos fiéis liderados por Peter Pan','Piratas liderados por Gancho','Os irmãos de Wendy em Londres','Crianças entrevistando uma escritora'],0,'Essa descrição aparece no quinto parágrafo.',179);
q('peter','Qual lista reúne as quatro aventuras mencionadas?',['Explorar cavernas, construir cabanas, navegar e combater piratas','Explorar cavernas, comprar livros, encolher e tomar chá','Construir cabanas, contar areia, dormir e ler uma notícia','Navegar, visitar a Bienal, abrir portas e jogar com a rainha'],0,'O texto apresenta essas quatro ações, incluindo combater piratas.',179);
q('peter','Quem era o grande inimigo de Peter Pan?',['Capitão Gancho','O coelho branco','A lagarta azul','A Rainha de Copas'],0,'O Capitão Gancho é apresentado como o grande inimigo de Peter.',177);
q('peter','Por que Wendy e os irmãos quiseram voltar?',['Sentiram saudades dos pais','Perderam uma passagem','A rainha ficou furiosa','O relógio estava atrasado'],0,'Depois dos dias mágicos, começaram a sentir saudades dos pais.',177);
q('peter','Em quais lugares a história acontece?',['Londres e Terra do Nunca','Espírito Santo e Rio de Janeiro','País das Maravilhas e Bienal','Uma praia e um bosque'],0,'A casa dos irmãos fica em Londres; a viagem os leva à Terra do Nunca.',180);
q('peter','O que acontece com os irmãos no final?',['Voltam para casa e ficam com memórias da viagem','Ficam para sempre na Terra do Nunca','Viram piratas de Gancho','Mudam para o País das Maravilhas'],0,'Eles voltam a Londres e acordam com a sensação de que a viagem talvez fosse um sonho.',180);
q('peter','Qual elemento caracteriza o conto fantástico estudado?',['Um elemento imaginário misturado ao mundo real','Somente instruções para uma experiência','Uma lista de compras','Uma notícia sobre um evento real'],0,'O livro destaca elementos fantasiosos e reais na mesma história.',180);
q('alice','Onde Alice estava com a irmã, e o que fazia?',['Debaixo de uma árvore, lendo um livro','Em um corredor, tomando chá','Na praia, contando areia','Em Londres, contando uma história'],0,'Essa informação está no começo da Parte 1.',181);
q('alice','O que o coelho branco vestia e carregava?',['Um colete e um relógio','Um gorro e uma chave','Roupas verdes e pó mágico','Uma coroa e um livro'],0,'O texto descreve um coelho com colete e relógio.',181);
q('alice','Por que Alice decidiu seguir o coelho?',['Ficou muito curiosa','Queria entrevistar uma escritora','Sentia saudades dos pais','Precisava combater piratas'],0,'A curiosidade fez Alice seguir o coelho.',182);
q('alice','Em qual mundo Alice foi parar?',['País das Maravilhas','Terra do Nunca','Londres','Espírito Santo'],0,'Alice cai no buraco e chega ao País das Maravilhas.',182);
q('alice','Como era o corredor?',['Cheio de portas trancadas','Cheio de barcos e piratas','Sem nenhuma porta','Feito de areia da praia'],0,'A Parte 2 começa com um corredor cheio de portas trancadas.',184);
q('alice','Por que Alice não conseguia passar pela portinha?',['A porta era pequena demais para ela','A chave não abria a porta','O coelho bloqueava a passagem','A rainha escondia a chave'],0,'Ela abriu a porta, mas não conseguia passar por ser grande demais.',183);
q('alice','O que aconteceu depois que Alice tomou um gole?',['Ela encolheu','Ela começou a voar','Ela adormeceu por cem anos','Ela ficou invisível'],0,'Alice encolheu até ficar do tamanho de uma pequena boneca.',183);
q('alice','Quais criaturas ela encontrou na floresta?',['Gato, lagarta, chapeleiro e lebre','Saci, Cuca, Boitatá e Gancho','Wendy, João, Miguel e Sininho','Três porquinhos e um lobo'],0,'A Parte 2 apresenta essas quatro criaturas.',184);
q('alice','Como a Rainha de Copas ficou quando Alice ganhou?',['Furiosa','Sonolenta','Apressada','Curiosa'],0,'A rainha ficou furiosa, ou seja, com muita raiva.',185);
q('alice','Qual acontecimento aparece perto do final?',['Alice acordou','Alice virou rainha','Alice ficou na floresta para sempre','Alice viajou para Londres'],0,'A Parte 3 diz: “E então… Alice acordou!”',185);
q('alice','Qual dúvida Alice tem no final?',['Se a aventura foi sonho ou realidade','Se Wendy era sua irmã','Se o coelho era um pirata','Se o livro era uma notícia'],0,'O final mantém a dúvida entre sonho e realidade.',185);
q('escrita','Qual frase usa corretamente maiúsculas, espaços e ponto-final?',['Alice seguiu o coelho.','alice seguiu o coelho.','Aliceseguiuocoelho.','Alice seguiu o coelho'],0,'Alice é nome próprio; a frase tem espaços e termina com ponto-final.',182);
q('escrita','Por que “Alice” começa com maiúscula no meio de uma frase?',['É um nome próprio','É a palavra mais longa','Tem três sílabas','Está depois de um espaço'],0,'Nomes próprios começam com letra maiúscula.',182);
q('escrita','Qual frase separa corretamente as palavras?',['O menino gostava de histórias fantásticas.','Omenino gostava dehistórias fantásticas.','O menino gostavade históriasfantásticas.','Omenino gostavadehistóriasfantásticas.'],0,'Cada palavra precisa de seu espaço.',108);
q('escrita','Qual lista está em ordem alfabética?',['Dama, Dominó, Ludo, Quebra-cabeça, Xadrez','Dominó, Dama, Quebra-cabeça, Ludo, Xadrez','Dama, Dominó, Ludo, Xadrez, Quebra-cabeça','Xadrez, Quebra-cabeça, Ludo, Dominó, Dama'],0,'Dama vem antes de Dominó; Q vem antes de X.',187);
q('escrita','Qual nome vem primeiro em ordem alfabética?',['Jogo da Memória','Jogo da Velha','Os dois ocupam a mesma posição','Não é possível comparar'],0,'O começo é igual. Compare M e V: M vem antes de V.',187);
q('escrita','Qual justificativa explica a ordem Memória → Velha?',['M vem antes de V','V vem antes de M','Memória tem mais letras','Velha é uma palavra menor'],0,'A ordem depende das letras, não do tamanho das palavras.',187);
q('escrita','Qual título escreve corretamente o nome da personagem?',['Descobertas de Inaiá','Descobertas de inaiá','descobertas de inaiá','DescobertasdeInaiá'],0,'O início do título e o nome Inaiá usam maiúscula.',109);
q('escrita','Qual frase organiza o trecho “ALEITURAÉ AMIGA DA IMA GINAÇÃO.”?',['A leitura é amiga da imaginação.','Aleitura é amiga da ima ginação.','A leituraé amiga da imaginação','a leitura é amiga da imaginação.'],0,'Separe as palavras, una imaginação e use maiúscula inicial e ponto-final.',197);
for(const [word,good,bad] of [['mundo','mun-do',['mu-ndo','mund-o','m-u-n-d-o']],['buraco','bu-ra-co',['bur-a-co','bu-rac-o','b-u-raco']],['país','pa-ís',['p-aís','país','pa-í-s']],['lagarta','la-gar-ta',['la-ga-rta','lag-ar-ta','la-gart-a']],['sorridente','sor-ri-den-te',['so-rri-den-te','sorr-i-den-te','sor-rid-ente']],['apressado','a-pres-sa-do',['a-pre-ssa-do','ap-res-sa-do','a-press-a-do']],['corrida','cor-ri-da',['co-rri-da','corr-i-da','cor-rid-a']],['passatempo','pas-sa-tem-po',['pa-ssa-tem-po','pass-a-tem-po','pas-sat-empo']]])q('silabas','Qual é a separação silábica correta de '+word.toUpperCase()+'?',[good,...bad],0,'A separação correta é '+good+'.',194);
q('silabas','Na separação silábica, o que acontece com RR e SS?',['Cada letra fica em uma sílaba diferente','As duas letras ficam sempre juntas','Uma das letras desaparece','As letras viram vogais'],0,'Compare sor-ri-den-te e a-pres-sa-do.',195);
q('silabas','Quando a palavra inteira não cabe no fim da linha, o que fazer?',['Dividi-la respeitando as sílabas e continuar na próxima linha','Separar em qualquer letra sem hífen','Apagar as letras que não cabem','Juntar a palavra à seguinte'],0,'Use um hífen no fim da linha e respeite as sílabas.',195);
q('silabas','Qual divisão de MENINA pode ser usada no fim da linha?',['meni- / na','men- / ina','menin- / a','m- / enina'],0,'Me-ni-na: podemos dividir entre ni e na. A barra indica a próxima linha.',196);
q('silabas','Quais contos são lembrados nos quadrinhos?',['Peter Pan, Alice e A Bela Adormecida','O Grúfalo, Inaiá e Os três porquinhos','Peter Pan, Inaiá e Chapeuzinho Vermelho','Alice, O Grúfalo e Sem Fim, Joaquim'],0,'As pistas são voar com pó de fada, seguir o coelho e dormir por cem anos.',193);
q('noticia','Sobre quem é a notícia?',['Ana Maria Machado','Maria Eduarda Gomes','Alice','Wendy'],0,'Ana Maria Machado é a escritora de quem a notícia trata.',200);
q('noticia','Em que evento a escritora estaria presente?',['Bienal do Livro','Uma partida da Rainha de Copas','Uma festa na Terra do Nunca','Um passeio dos três porquinhos'],0,'O primeiro parágrafo menciona a Bienal do Livro.',200);
q('noticia','O que ela faria no evento?',['Falaria sobre obras e seria entrevistada por crianças','Compraria uma passagem para Londres','Contaria grãos de areia na praia','Jogaria com a Rainha de Copas'],0,'Essas duas ações aparecem no primeiro parágrafo.',200);
q('noticia','Que pergunta de Luísa inspirou o livro?',['Se poderia contar os grãos de areia da praia','Se poderia voar com pó mágico','Por que o coelho estava atrasado','Como abrir uma portinha'],0,'A pergunta aconteceu na praia, cerca de quarenta anos antes.',200);
q('noticia','Qual é o assunto principal da notícia?',['A atuação profissional e as inspirações da escritora','Somente um passeio na praia','Somente animais do mar','As regras de um jogo'],0,'O texto reúne a carreira, o novo livro e as inspirações da autora.',200);
q('noticia','Como se chama o título de uma notícia?',['Manchete','Personagem','Desfecho','Sílaba'],0,'O livro ensina: o título das notícias é chamado de manchete.',200);
q('noticia','Quem escreveu esta notícia?',['Maria Eduarda Gomes','Ana Maria Machado','Luísa','Peter Pan'],0,'Maria Eduarda Gomes aparece na autoria; Ana Maria Machado é a pessoa sobre quem se fala.',200);
q('noticia','Qual é a data de publicação indicada?',['14 de setembro de 2024','14 de setembro de 1941','7 de outubro de 2026','25 de março de 2025'],0,'A autoria e a referência indicam 14/09/2024.',199);
q('noticia','Qual descrição corresponde ao gênero notícia?',['Informa sobre pessoas e acontecimentos reais','Sempre conta uma aventura mágica','Só lista sílabas separadas','Só ensina regras de um jogo'],0,'Essa é a definição apresentada na página 201.',201);
q('noticia','Em qual meio podemos encontrar notícias?',['Em um jornal','Em um relógio','Em uma chave','Em um gorro'],0,'Jornais são meios de comunicação que divulgam notícias.',201);
q('noticia','O que o menino de Sem Fim, Joaquim deseja fazer?',['Contar tudo à sua volta','Viajar à Terra do Nunca','Seguir um coelho','Combater piratas'],0,'O livro fala de contar folhas e grãos de areia e descobrir o infinito.',199);
q('noticia','Quem lia histórias para Ana Maria Machado quando pequena?',['Sua avó','Peter Pan','A Rainha de Copas','O Capitão Gancho'],0,'A notícia relaciona sua criatividade às histórias lidas pela avó.',199);
const WRITING={
lendas:[['Responda em letra cursiva: que animal é o Boitatá?','O Boitatá é uma cobra de fogo.',107],['Copie em letra cursiva: O Saci-Pererê consegue ficar invisível.','Observe as maiúsculas, os espaços e o ponto-final.',107],['Imagine por que a Cuca dorme tão pouco. Escreva sua opinião.','Resposta pessoal. Explique sua ideia; a lenda não dá um motivo.',107]],
peter:[['Escreva as quatro aventuras vividas na Terra do Nunca.','Exploraram cavernas, construíram cabanas em árvores, navegaram por mares agitados e combateram piratas.',179],['Escreva quem participa da história, onde ela acontece e como termina.','Personagens: Peter Pan, Wendy, João, Miguel, Fada Sininho, Meninos Perdidos e Capitão Gancho. Lugares: Londres e Terra do Nunca. Os irmãos voltam para casa; Peter e Sininho voltam à terra da magia.',180],['Por que a viagem deixou memórias inesquecíveis? Escreva sua opinião e justifique.','Resposta pessoal. Você pode mencionar uma aventura do texto e explicar por que seria inesquecível.',179]],
alice:[['Crie uma resposta estranha: qual é o chá preferido do chapeleiro maluco?','Resposta criativa, sem gabarito único. O texto não diz qual chá ele prefere.',185],['Crie uma resposta estranha: por que o gato tem um sorriso largo?','Resposta criativa, sem gabarito único. O motivo não é informado no texto.',185],['Desenhe o jogo que você imagina que a Rainha de Copas jogava e explique como seria.','Resposta pessoal. O texto não revela qual jogo era.',186],['Você acha que a aventura foi real ou um sonho? Escreva sua opinião e explique.','Resposta pessoal com justificativa. Você pode usar “Alice acordou” para defender a ideia de sonho; o final conserva a dúvida.',186],['Como você acha que Alice se sentiu no mundo estranho? Explique.','Resposta pessoal. Relacione sua ideia a algum acontecimento da história.',186]],
escrita:[['Reescreva com espaços e letra cursiva: Omeninogostavadehistóriasfantásticas.','O menino gostava de histórias fantásticas.',108],['Copie os títulos em letra cursiva: Descobertas de Inaiá / O Grúfalo.','Observe as maiúsculas em Descobertas, Inaiá, O e Grúfalo.',109],['Crie outro título para um desses livros: Descobertas de Inaiá ou O Grúfalo.','Resposta criativa. Comece o título com maiúscula e preserve a maiúscula dos nomes próprios.',109],['Em letra cursiva, escreva um lugar que gostaria de explorar e uma história que leria para Alice.','Resposta pessoal. Confira a maiúscula dos nomes próprios e o espaço entre as palavras.',183],['Escreva em ordem alfabética: Jogo da Velha / Jogo da Memória. Depois explique sua ordem.','Jogo da Memória; Jogo da Velha. M vem antes de V.',187],['Organize e copie em cursiva: ALEITURAÉ AMIGA DA IMA GINAÇÃO. JUNTAS ELAS PO–DEM NOS LEVAR PARA MUNDOSMÁGICOS, CHEIOSDE AVENTURAS, DE PER SONAGENS INCRÍVEIS, DE LUGARES FANTÁSTICOS, MISTE RIOSOS E DIVER TIDOS','A leitura é amiga da imaginação. Juntas elas podem nos levar para mundos mágicos, cheios de aventuras, de personagens incríveis, de lugares fantásticos, misteriosos e divertidos.',197]],
silabas:[['Separe as sílabas: mundo, gato, país, lagarta, garota.','mun-do; ga-to; pa-ís; la-gar-ta; ga-ro-ta.',194],['Separe as sílabas: sorridente, apressado, corrida, passatempo.','sor-ri-den-te; a-pres-sa-do; cor-ri-da; pas-sa-tem-po. RR e SS ficam em sílabas diferentes.',195],['Escreva uma frase com “menina”. Imagine que a palavra não cabe no fim da linha e continue na próxima.','Uma divisão possível: meni- no fim da linha e na na linha seguinte. Também é possível me- / nina.',196],['Escreva o nome do conto de cada pista: voar com pó de fada; seguir um coelho; dormir por cem anos.','Peter Pan; Alice no País das Maravilhas; A Bela Adormecida.',193]],
noticia:[['Escreva o nome da pessoa sobre quem é a notícia e o nome de quem a escreveu.','Sobre Ana Maria Machado. Escrito por Maria Eduarda Gomes.',200],['Escreva a pergunta de Luísa que inspirou Sem Fim, Joaquim.','Ela perguntou se poderia contar os grãos de areia da praia.',200],['Escreva dois lugares ou meios onde podemos encontrar notícias.','Exemplos: jornais, sites de notícias, televisão, rádio e revistas.',201],['Explique com suas palavras o que é uma notícia.','É um texto que transmite informações sobre pessoas e acontecimentos reais, divulgado em meios de comunicação.',201]]};
